apiVersion: v1
kind: Service
metadata:
  labels:
    app: catalog
    application: coolstore
    component: catalog
  name: catalog-mongodb
spec:
  ports:
  - name: mongo
    port: 27017
    protocol: TCP
    targetPort: 27017
  selector:
    deploymentconfig: catalog-mongodb
  sessionAffinity: None
  type: ClusterIP
